### PR TITLE
Changes default units for 0 from bits to Bytes

### PR DESCRIPTION
**Pull request by mintsoft**
Not sure on your thoughts on this, I appreciate this might be contentious. However most users expect to see things in bytes most of the time, it seems like a more sensible default unit given that everything else defaults to Bytes.

I was going to make it so that it choses the default based on whether you used FromBytes or FromBits, but I thought I'd see what your thoughts are first with this. Happy to change anything you deem appropriate or squash history etc.

Fixes : https://github.com/omar/ByteSize/issues/42

### CODE REVIEW

**Comment by mintsoft** [comment]
@omar Any thoughts on this?

**Comment by 0xced** [comment]
I personally agree with this, using `B` instead of `b` for 0 is what I would expect.

**Comment by omar** [comment]
I think this makes sense. It's a bit of a breaking change so I'll probably hold off on including it until v3?

**Comment by mintsoft** [comment]
Yeah sounds cool @omar do you need/want me to resolve the conflicts or will you do that as part of v4?

**Comment by 0xced** [comment]
Both `0b` and `0B` are correct so I would not deem this a breaking change. Also, from the API compatibility point of view, this is definitely not a [breaking change](https://docs.microsoft.com/en-us/dotnet/core/compatibility/). I would consider merging this pull request in a minor release with a proper entry in the changelog.

**Comment by omar** [comment]
Rethinking this some more, my initial hesitation was because we're changing how the `LargestWholeNumberBinarySymbol` works to change the behavior of ToString.

This change is meant to modify how ToString method works indirectly, I'm rethinking this. I think it might be best for the sake of clarity to do this change in the ToString method. Something as simple as this:

```
if (this.Bytes == 0)
    return "0 B";
```

It's clear and localized where as the change in the properties adds a layer of indirection.

**Pull request merged**
