### PR TITLE
Migrate to csproj

### LINKED ISSUE #35: Migrate to csproj
I'm using this library in an app that runs inside a docker container. Due to having been built with project.json format, this library requires an sdk image to run, which is significantly bigger than the runtime image. Switching to csproj should fix it.

### PR DESCRIPTION
**Pull request by Tyrrrz**
Fixes #35

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Tested with `dotnet build` and `dotnet test`, it works.
The library targets `.netstd2.0` and `.net45` for simpler dependency graph compatibility. The tests are running `.netcoreapp2.1`.

**Comment by Tyrrrz** [comment]
I just realized you can't build with net45 target on Linux :(
This can be resolved if we move to [appveyor](https://appveyor.com)

**Comment by omar** [comment]
Thanks for this. I went ahead and fixed the Travis CI build by using Docker to build the project.

**Comment by Tyrrrz** [comment]
Nice. :)
Thank you for the project.

**Pull request merged**
