### PR TITLE
General code cleanup (without any semantic changes)

### PR DESCRIPTION
**Pull request by 0xced**
* Use 4 spaces instead of tabs everywhere
* Remove all unused imports
* Cleanup ByteSizeLib.Tests.Binary namespace
* Fix typos
* Remove unused private setters

### CODE REVIEW

**Comment by clintnetwork** [comment]
Hi, @0xced any news about this PR? does this repo still active?

**Comment by 0xced** [comment]
Like many open source projects, ByteSize rests squarely on the shoulders of a single person, here, @omar. Let's hope he can find some time to go over the pull requests. Publishing on NuGet should be straightforward since a [CI workflow](https://github.com/omar/ByteSize/blob/master/.github/workflows/ci.yml) already exists for this repository.

**Comment by omar** [comment]
Thank you for changes. This fell through the cracks.

**Comment by 0xced** [comment]
Awesome, thanks for the very quick reply ! 👍 Don't forget to also have a look at #49, #50 and #51. 😉

**Pull request merged**
